# Generated by Django 3.1.3 on 2020-11-20 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%d/%m/%Y %H:%M:%S'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='createdAt',
            field=models.DateTimeField(verbose_name='%d/%m/%Y %H:%M:%S'),
        ),
    ]
